// ================================================================
// TODAY'S CHALLENGE — rotation pool (single source of truth)
// Loaded by the operator dashboard card and by /challenge.html.
// Rotation: CHALLENGES[Math.floor(Date.now()/86400000) % CHALLENGES.length]
// Keep order stable — reordering changes which challenge lands on which day.
// ================================================================
window.CD_CHALLENGES = [
  { title: 'Golden Hour Portrait',
    desc: 'Capture a portrait during golden hour. Focus on warm tones and backlighting.',
    tips: ['Shoot with the sun behind your subject and expose for the face.',
           'Open up to f/1.8–f/2.8 and let the background melt away.',
           'Push white balance warm — Shade preset or around 6500K.'] },
  { title: 'Street Scene',
    desc: 'Capture a candid street moment with strong composition.',
    tips: ['Pre-focus or use continuous AF — the moment will not wait.',
           'Build layers: something in the foreground, the subject, and depth behind.',
           'Shoot a short burst and pick the decisive frame later.'] },
  { title: 'Minimalist Still Life',
    desc: 'Arrange 3 objects and create a simple, clean composition.',
    tips: ['One light source, one shadow — keep it ruthlessly simple.',
           'Leave negative space so the subject can breathe.',
           'Shoot top-down or straight-on for strong graphic shapes.'] },
  { title: 'Macro Details',
    desc: 'Find a small subject and capture it in extreme detail.',
    tips: ['Get close — fill the frame with texture.',
           'Brace the camera or raise the shutter speed to kill shake.',
           'Manual focus usually beats autofocus at macro distances.'] },
  { title: 'Reflection Hunt',
    desc: 'Find a reflection — water, glass, mirror — and make it the subject.',
    tips: ['Expose for the reflection, not the light source.',
           'Get low: puddles turn into mirrors at grazing angles.',
           'Let the reflection dominate the frame — flip the composition.'] },
  { title: 'Blue Hour Cityscape',
    desc: 'Shoot the city in the 20 minutes after sunset, when the sky goes electric blue.',
    tips: ['Arrive before sunset and lock your composition early.',
           'Expose for the sky; let the streetlights bloom.',
           'A tripod helps — otherwise brace and keep ISO under 3200.'] },
  { title: 'Leading Lines',
    desc: 'Find lines — roads, rails, fences, shadows — that pull the eye to your subject.',
    tips: ['Place the subject where the lines converge.',
           'Get low to exaggerate the lines in the foreground.',
           'Curved lines slow the eye; straight lines rush it. Choose on purpose.'] },
  { title: 'Silhouette Story',
    desc: 'Expose for a bright sky and let your subject go fully black.',
    tips: ['Meter off the brightest part of the sky, then recompose.',
           'Pick subjects with clean, readable outlines.',
           'Shoot slightly underexposed — muddy gray is the enemy.'] },
  { title: 'Panning Motion',
    desc: 'Track a moving subject at a slow shutter speed so it stays sharp against a blurred world.',
    tips: ['Start at 1/30s and pan smoothly from the hips.',
           'Use continuous AF and burst mode.',
           'Follow through after the shutter — stopping early kills the shot.'] },
  { title: 'Window Light Portrait',
    desc: 'One window, one subject. The softest studio you will ever own.',
    tips: ['Put the subject at a 45° angle to the window, not flat against it.',
           'The farther from the window, the softer and dimmer the falloff.',
           'Expose for the lit side of the face; let the shadow side fall.'] },
  { title: 'Shadow Play',
    desc: 'Shoot in harsh light and make the shadows the actual subject.',
    tips: ['Look down as much as through the viewfinder — shadows live on the ground.',
           'Underexpose a stop to deepen the blacks.',
           'Patterns beat blobs: blinds, fences, leaves.'] },
  { title: 'Monochrome Mood',
    desc: 'Shoot in black and white today. Think in tones, not colors.',
    tips: ['Set the camera to monochrome so you see tones while shooting.',
           'Chase contrast: deep blacks against bright whites.',
           'Texture and shape carry the frame when color is gone.'] },
  { title: 'Negative Space',
    desc: 'Make your subject tiny. Let emptiness do the heavy lifting.',
    tips: ['The subject should occupy under a fifth of the frame.',
           'Keep the empty area clean — one distraction ruins it.',
           'Place the subject off-center, looking or moving into the space.'] },
  { title: 'Frame Within a Frame',
    desc: 'Shoot through a doorway, window, arch, or branches to frame your subject twice.',
    tips: ['Expose for the subject, not the foreground frame.',
           'Use the foreground frame to hide clutter at the edges.',
           'A wide aperture softens the inner frame into a vignette.'] },
  { title: 'Color Pop',
    desc: 'Find one bold color standing out against a neutral scene.',
    tips: ['Desaturate the scene in your mind first — then hunt the exception.',
           'Get close enough that the color owns the frame.',
           'Overcast light makes single colors sing.'] },
  { title: 'Night Handheld',
    desc: 'Shoot after dark with no tripod. Embrace the grain.',
    tips: ['Find the fastest lens you own and open it all the way.',
           'Brace against a wall, exhale, shoot between heartbeats.',
           'A little motion blur in the lights reads as atmosphere, not error.'] },
  { title: 'Symmetry',
    desc: 'Find or build perfect balance — mirror images, centered subjects, calm frames.',
    tips: ['Center the subject dead-on; near-symmetry looks like a mistake.',
           'Reflections are symmetry on demand.',
           'Break it once, deliberately — one off-center detail adds tension.'] },
  { title: 'Texture Study',
    desc: 'Get close to a surface — bark, rust, fabric, stone — and photograph pure texture.',
    tips: ['Side light rakes across texture; front light flattens it.',
           'Fill the entire frame — no context, just surface.',
           'Convert to black and white to judge the texture honestly.'] },
  { title: 'Candid Emotion',
    desc: 'Capture a genuine, unposed expression — laughter, focus, surprise.',
    tips: ['Stay ready before the moment, invisible during it.',
           'A longer lens lets you work without intruding.',
           'Shoot through the moment — the frame after the laugh is often the keeper.'] },
  { title: 'Silky Water',
    desc: 'Slow the shutter and turn moving water into silk.',
    tips: ['Start at 1/4s; go slower as the light allows.',
           'Brace the camera on a rock, bag, or railing — no tripod needed.',
           'Include one sharp anchor (a rock, a branch) so the blur has contrast.'] },
  { title: 'Shooting Into the Light',
    desc: 'Point the camera at the light source and control the flare.',
    tips: ['Partially block the sun with your subject for controlled flare.',
           'Stop down to f/11+ to turn flare into a starburst.',
           'Shield the front element with your hand to kill unwanted haze.'] },
  { title: 'Urban Geometry',
    desc: 'Turn buildings into abstract shapes — crop out the context.',
    tips: ['Look up. The good stuff is above the storefronts.',
           'Tight crops turn architecture into pure pattern.',
           'Harsh midday light carves the strongest shapes.'] },
  { title: 'The Decisive Detail',
    desc: 'Tell a whole story in one small detail — hands, shoes, a worn handle.',
    tips: ['Ask what single detail proves the story happened.',
           'Get close enough that the detail fills the frame.',
           'Shallow depth of field isolates the detail from the noise.'] },
  { title: 'Bad Weather, Good Photos',
    desc: 'Shoot in rain, fog, or flat gray light — the conditions everyone avoids.',
    tips: ['Fog simplifies: distant clutter dissolves into layers.',
           'Protect the camera under a jacket; wipe the lens often.',
           'Wet surfaces double your reflections and saturate colors.'] },
  { title: 'Worm\'s-Eye View',
    desc: 'Put the camera near the ground and photograph the world from below.',
    tips: ['Flip the screen up — your knees will thank you.',
           'A wide lens near the ground makes the ordinary monumental.',
           'Watch the sky exposure; it will want to blow out.'] },
  { title: 'High Contrast Drama',
    desc: 'Deep blacks, bright whites, nothing in between. Make it theatrical.',
    tips: ['Expose so the shadows crush and the highlights hold.',
           'Side light sculpts; front light flattens.',
           'One strong subject beats a busy scene.'] },
  { title: 'Everyday Hero',
    desc: 'Take the most boring object within reach and light it like a hero.',
    tips: ['One directional light source — a lamp, a window, a phone.',
           'Dark background, clean surface, zero clutter.',
           'Shoot the angle nobody sees: from below, from an inch away.'] },
  { title: 'Freeze the Moment',
    desc: 'Crank the shutter past 1/1000s and freeze something the eye can\'t catch.',
    tips: ['Shutter priority at 1/1000s or faster; let ISO float.',
           'Burst mode is mandatory — timing alone won\'t do it.',
           'Water, sports, pets, kids: motion is everywhere once you look.'] },
  { title: 'Environmental Portrait',
    desc: 'Photograph a person inside their world — workspace, kitchen, garage.',
    tips: ['Include the environment, but keep the person the clear subject.',
           'Ask them to do something real, not pose.',
           'A 35–50mm lens keeps the space honest without distortion.'] },
  { title: 'Light Trail Hunt',
    desc: 'After dark, turn moving lights — cars, bikes, sparklers — into ribbons.',
    tips: ['Set the camera down solid: wall, railing, bag.',
           'Start at 2–4 seconds and adjust from the first frame.',
           'Compose with the dark first, then let the trails draw through it.'] }
];
