/* Cameras Decoded — Quick drill pool.
   One drill per local day, rotating: index = localDayIndex % pool.length.
   Fields: t = drill title, q = question, c = 3 choices, a = correct index,
   ok = correct feedback, no = wrong-answer feedback.
   Keep copy tight, beginner-friendly, typo-free. */
window.CDDrills = [
  { t: "Spot the exposure fix",
    q: "Your subject is sharp, but motion in the background looks frozen. Which control adds motion blur?",
    c: ["Narrow the aperture", "Use a slower shutter speed", "Lower the ISO"], a: 1,
    ok: "Correct. A slower shutter leaves the sensor exposed longer, so movement records as blur.",
    no: "Not quite. Aperture and ISO change exposure, but shutter speed controls how motion is rendered." },
  { t: "Freeze the action",
    q: "A cyclist speeds past and every frame is a blurry streak. Which change freezes the action?",
    c: ["Widen the aperture", "Use a faster shutter speed", "Raise the ISO"], a: 1,
    ok: "Correct. A faster shutter captures a thinner slice of time, freezing motion.",
    no: "Not quite. Only shutter speed decides whether motion freezes or streaks." },
  { t: "Face in the shadows",
    q: "Your subject\u2019s face is dark against a bright window. What is the fastest fix?",
    c: ["Spot meter on the face", "Narrow the aperture", "Lower the ISO"], a: 0,
    ok: "Correct. Spot metering exposes for the face instead of the bright window.",
    no: "Not quite. The camera exposed for the window \u2014 metering is the fix, not exposure settings." },
  { t: "Blurry indoors",
    q: "Indoor shots keep coming out blurry, but the brightness looks right. What is most likely wrong?",
    c: ["The shutter speed is too slow", "The ISO is too high", "The aperture is too wide"], a: 0,
    ok: "Correct. In dim light the camera drops the shutter speed, and hand shake blurs the frame.",
    no: "Not quite. The exposure is fine \u2014 the blur is motion, which points at shutter speed." },
  { t: "Creamy background",
    q: "You want that creamy blurred background in a portrait. Which setting matters most?",
    c: ["A wide aperture like f/1.8", "A fast shutter like 1/1000", "A low ISO like 100"], a: 0,
    ok: "Correct. A wide aperture shrinks depth of field and melts the background.",
    no: "Not quite. Background blur comes from shallow depth of field \u2014 that is aperture." },
  { t: "Sharp front to back",
    q: "A landscape needs sharpness from the flowers at your feet to the mountains. What do you do?",
    c: ["Narrow the aperture to f/11", "Open up to f/1.8", "Raise the ISO"], a: 0,
    ok: "Correct. A narrow aperture deepens the focus zone from near to far.",
    no: "Not quite. Wide apertures give thin focus \u2014 landscapes want the opposite." },
  { t: "Night grain",
    q: "Your night photo is full of ugly grain. What caused it?",
    c: ["Very high ISO", "A slow shutter speed", "A wide aperture"], a: 0,
    ok: "Correct. Cranking the ISO amplifies the signal \u2014 and the noise with it.",
    no: "Not quite. Shutter and aperture do not create grain \u2014 high ISO does." },
  { t: "Orange indoors",
    q: "Your indoor photos look orange under the lamps. What is the fix?",
    c: ["Set white balance to tungsten", "Raise the ISO", "Open the aperture"], a: 0,
    ok: "Correct. The orange cast means white balance does not match the warm bulbs.",
    no: "Not quite. An orange color cast is a white balance problem, not exposure." },
  { t: "Blue shade",
    q: "Photos taken in open shade look too blue. What fixes it?",
    c: ["Warm up the white balance", "Lower the ISO", "Use a faster shutter"], a: 0,
    ok: "Correct. Shade is naturally cool \u2014 warming the white balance neutralizes it.",
    no: "Not quite. A blue cast is white balance, not an exposure setting." },
  { t: "Harsh noon",
    q: "It is noon and faces have harsh shadows under eyes and noses. What is the quickest fix?",
    c: ["Move the subject into open shade", "Open the aperture wider", "Raise the ISO"], a: 0,
    ok: "Correct. Open shade turns the whole sky into a giant soft light.",
    no: "Not quite. No setting softens overhead sun \u2014 changing the light does." },
  { t: "Golden light",
    q: "You want warm, flattering portrait light. When should you shoot?",
    c: ["Near sunrise or sunset", "At high noon", "Under office fluorescents"], a: 0,
    ok: "Correct. Low, warm sun flatters skin and sculpts faces.",
    no: "Not quite. Harsh noon sun and office lights are the least flattering options." },
  { t: "Off-center",
    q: "Your compositions feel static with the subject always dead center. What should you try?",
    c: ["Place the subject on a thirds intersection", "Zoom in tighter", "Shoot from lower down"], a: 0,
    ok: "Correct. Off-center placement on the thirds grid creates tension and balance.",
    no: "Not quite. Tighter or lower does not fix static composition \u2014 placement does." },
  { t: "Leading lines",
    q: "A road runs through your landscape but the viewer\u2019s eye wanders off. How do you use it?",
    c: ["Let the road lead into the frame toward the subject", "Center the road", "Crop the road out"], a: 0,
    ok: "Correct. Leading lines pull the viewer straight to your subject.",
    no: "Not quite. Lines are tools \u2014 aim them at what matters." },
  { t: "Split horizon",
    q: "Your seascape\u2019s horizon sits dead center and the shot feels split in two. Fix?",
    c: ["Put the horizon on the upper or lower third", "Tilt the camera", "Zoom out wider"], a: 0,
    ok: "Correct. An off-center horizon lets the sky or foreground breathe.",
    no: "Not quite. A centered horizon divides the frame \u2014 commit to sky or foreground." },
  { t: "Eyes first",
    q: "In a portrait the nose is sharp but the eyes are soft. What went wrong?",
    c: ["Focus locked on the wrong spot", "The aperture was too narrow", "The ISO was too low"], a: 0,
    ok: "Correct. Focus on the nearest eye \u2014 that is where viewers look first.",
    no: "Not quite. This is a focus placement miss, not a settings problem." },
  { t: "Steady hands",
    q: "What is a safe handheld shutter speed with a 50mm lens?",
    c: ["1/60s or faster", "1/8s", "A full second"], a: 0,
    ok: "Correct. The reciprocal rule: shutter speed at least 1/focal length.",
    no: "Not quite. 1/8s handheld on a 50mm will shake \u2014 stay at 1/60 or faster." },
  { t: "Pan with it",
    q: "You want a sharp cyclist against a streaked background. What is the technique?",
    c: ["Pan with the subject at a slow shutter speed", "Freeze everything at 1/4000", "Use burst mode only"], a: 0,
    ok: "Correct. Tracking the subject keeps it sharp while the world streaks past.",
    no: "Not quite. Freezing everything kills the feeling of speed \u2014 pan instead." },
  { t: "Sunset silhouette",
    q: "You want a dramatic sunset silhouette of a lone tree. How do you expose?",
    c: ["Meter for the bright sky", "Meter for the tree", "Brighten the shadows later"], a: 0,
    ok: "Correct. Exposing for the sky drops the tree into a black shape.",
    no: "Not quite. Metering for the tree would brighten it and kill the silhouette." },
  { t: "Blown highlights",
    q: "The histogram is slammed against the right edge. What does that mean?",
    c: ["Highlights are blown out", "The photo is too dark", "The colors are wrong"], a: 0,
    ok: "Correct. Data piled on the right means highlights with no detail left.",
    no: "Not quite. The right edge is the bright side \u2014 those tones are clipping." },
  { t: "Crushed shadows",
    q: "The histogram is slammed against the left edge. What does that mean?",
    c: ["Shadows are crushed to black", "Highlights are blown out", "Nothing \u2014 it is fine"], a: 0,
    ok: "Correct. Data piled on the left means shadow detail lost to black.",
    no: "Not quite. The left edge is the shadow side." },
  { t: "Gray snow",
    q: "Your snow scene came out gray instead of white. What is the fastest fix?",
    c: ["Add +1 to +2 exposure compensation", "Lower the ISO", "Narrow the aperture"], a: 0,
    ok: "Correct. The meter underexposes bright scenes \u2014 positive compensation overrides it.",
    no: "Not quite. The meter was fooled by all that brightness; compensation is the override." },
  { t: "Backlit subject",
    q: "You are shooting into the sun and your subject is a dark blob. What is the quick fix?",
    c: ["Add fill flash or a reflector", "Narrow the aperture", "Lower the ISO"], a: 0,
    ok: "Correct. Backlit subjects need light added to the shadow side.",
    no: "Not quite. Settings cannot invent light on a dark face \u2014 add some." },
  { t: "F-numbers",
    q: "Which aperture gives the shallowest depth of field?",
    c: ["f/1.8", "f/8", "f/16"], a: 0,
    ok: "Correct. A smaller f-number means a wider opening and thinner focus.",
    no: "Not quite. F-numbers run backward \u2014 small number, big opening." },
  { t: "Worth the tripod",
    q: "When is a tripod most worth the hassle?",
    c: ["Long exposures at night", "Bright sunny portraits", "Fast action sports"], a: 0,
    ok: "Correct. Exposures lasting seconds cannot be handheld.",
    no: "Not quite. Bright light and fast action do not need one \u2014 long exposures do." },
  { t: "Catch the peak",
    q: "You are photographing your dog sprinting. Which drive mode helps?",
    c: ["Continuous burst", "Single shot", "Self-timer"], a: 0,
    ok: "Correct. Burst mode stacks the odds across the peak of the action.",
    no: "Not quite. A single shot will likely miss the peak moment." },
  { t: "Tracking focus",
    q: "Your camera keeps locking focus then losing a running kid. Which AF mode?",
    c: ["Continuous AF (AF-C)", "Single AF (AF-S)", "Manual focus"], a: 0,
    ok: "Correct. Continuous AF tracks subjects that keep moving.",
    no: "Not quite. Single AF locks once \u2014 movers need continuous tracking." },
  { t: "Still scene",
    q: "For a still landscape on a tripod, which focus mode?",
    c: ["Single AF (AF-S)", "Continuous AF (AF-C)", "Manual always"], a: 0,
    ok: "Correct. Nothing is moving \u2014 lock focus once and shoot.",
    no: "Not quite. Continuous AF hunts on still scenes." },
  { t: "Fill the shadows",
    q: "Harsh sun is carving dark shadows under your subject\u2019s eyes. Besides finding shade, what helps?",
    c: ["A touch of fill flash", "Higher ISO", "A faster shutter"], a: 0,
    ok: "Correct. A kiss of flash lifts the shadows without killing the sunlight.",
    no: "Not quite. Exposure tweaks cannot fill shadows \u2014 add light." },
  { t: "Soften the flash",
    q: "Direct flash looks harsh and flat. What is the quick improvement?",
    c: ["Bounce it off the ceiling or a wall", "Move closer", "Just raise the ISO instead"], a: 0,
    ok: "Correct. Bouncing turns a small hard flash into a big soft one.",
    no: "Not quite. Moving closer only makes direct flash harsher." },
  { t: "Add depth",
    q: "Your landscape feels flat and distant. What adds depth?",
    c: ["Include close foreground interest", "Use a longer lens", "Raise the ISO"], a: 0,
    ok: "Correct. Near-far layers give the eye a path into the scene.",
    no: "Not quite. Longer lenses compress a scene \u2014 foreground creates depth." },
  { t: "Power of empty",
    q: "A lone bird in a vast sky feels powerful. Which principle is at work?",
    c: ["Negative space", "Rule of thirds", "Leading lines"], a: 0,
    ok: "Correct. Empty space isolates the subject and amplifies it.",
    no: "Not quite. Here it is the emptiness doing the work." },
  { t: "Shoot RAW",
    q: "You want maximum editing flexibility later. Which format?",
    c: ["RAW", "Small JPEG", "PNG"], a: 0,
    ok: "Correct. RAW keeps all the sensor data for white balance and exposure recovery.",
    no: "Not quite. Compressed formats throw away the data you would want back." },
  { t: "Blue hour",
    q: "The sky is deep blue after sunset and city lights are glowing. What is this window called?",
    c: ["Blue hour", "Golden hour", "High noon"], a: 0,
    ok: "Correct. Blue hour\u2019s cool ambient balances beautifully with warm city lights.",
    no: "Not quite. Golden hour is before sunset \u2014 this cool glow after is blue hour." },
  { t: "Flattering lens",
    q: "Which lens flatters faces most for portraits?",
    c: ["85mm", "16mm", "24mm"], a: 0,
    ok: "Correct. Short telephotos compress features flatteringly.",
    no: "Not quite. Wide lenses stretch whatever is closest \u2014 usually the nose." },
  { t: "Edge stretch",
    q: "At 16mm, people at the edges of your group photo look stretched. Fix?",
    c: ["Step back and zoom in", "Get closer", "Change the lighting"], a: 0,
    ok: "Correct. Wide angles stretch edges \u2014 longer focal lengths keep people natural.",
    no: "Not quite. That is perspective distortion from the wide lens, not light." },
  { t: "Clean backdrop",
    q: "What makes the best portrait background?",
    c: ["Simple and uncluttered", "Busy with lots of detail", "Bright neon signs"], a: 0,
    ok: "Correct. Clean backgrounds keep all attention on the face.",
    no: "Not quite. Busy backgrounds compete with your subject." },
  { t: "Eyes alive",
    q: "Your portrait subject\u2019s eyes look lifeless. What is missing?",
    c: ["Catchlights from a light source", "More saturation", "Sharper focus"], a: 0,
    ok: "Correct. A spark of reflected light brings eyes alive.",
    no: "Not quite. Eyes need a light source to reflect \u2014 that is the sparkle." },
  { t: "Cloudy day",
    q: "It is overcast \u2014 bad news for portraits?",
    c: ["No \u2014 clouds are a giant softbox", "Yes \u2014 pack up", "Only shoot black and white"], a: 0,
    ok: "Correct. Overcast light is soft, even, and flattering.",
    no: "Not quite. Clouds diffuse the sun beautifully \u2014 ideal portrait light." },
  { t: "Free studio",
    q: "What is the best free portrait light indoors?",
    c: ["A large window, subject angled toward it", "Overhead ceiling lights", "The bathroom mirror"], a: 0,
    ok: "Correct. Big, soft window light sculpts faces for free.",
    no: "Not quite. Overhead indoor light is small and harsh by comparison." },
  { t: "Straight horizon",
    q: "Your seascapes always tilt slightly. What helps in-camera?",
    c: ["Turn on the electronic level", "Fix it later every time", "Tilt more on purpose"], a: 0,
    ok: "Correct. The in-camera level nails straight horizons while shooting.",
    no: "Not quite. Fixing every shot later wastes time \u2014 level it now." },
  { t: "Moonrise",
    q: "You want the moon huge behind a city skyline. What helps?",
    c: ["A long telephoto from far away", "A wide angle up close", "A higher ISO"], a: 0,
    ok: "Correct. Telephoto compression stacks distant layers dramatically.",
    no: "Not quite. Wide angles shrink distant objects \u2014 go long." },
  { t: "Star trails",
    q: "Your stars are trailing into little lines. What is happening?",
    c: ["The exposure is too long", "The ISO is too low", "The white balance is wrong"], a: 0,
    ok: "Correct. Earth\u2019s rotation streaks stars past roughly 20\u201330 seconds.",
    no: "Not quite. Trailing is motion over time \u2014 shorten the exposure." },
  { t: "Glassy water",
    q: "A lake perfectly mirrors the mountains. When is water calmest?",
    c: ["Early morning", "Windy midday", "Breezy evening"], a: 0,
    ok: "Correct. Dawn air is stillest \u2014 glassy water mirrors the scene.",
    no: "Not quite. Wind ripples kill reflections \u2014 shoot when the air is calm." },
  { t: "Fill the frame",
    q: "Your subject is tiny in the frame with acres of nothing around it. Fix?",
    c: ["Move closer or zoom in", "Crop it later", "Raise the ISO"], a: 0,
    ok: "Correct. Filling the frame in-camera keeps maximum quality.",
    no: "Not quite. Heavy crops throw away pixels \u2014 get closer first." },
  { t: "Tall subject",
    q: "You are shooting a tall waterfall and it feels cramped. What should you try?",
    c: ["Turn the camera vertical", "Step further back", "Use flash"], a: 0,
    ok: "Correct. Match the frame shape to the subject\u2019s shape.",
    no: "Not quite. Tall subjects want tall frames." },
  { t: "Midday texture",
    q: "The midday light is flat and harsh. What still photographs well right now?",
    c: ["Textures, details, and black-and-white", "Portraits in direct sun", "Sunsets"], a: 0,
    ok: "Correct. Harsh light carves texture \u2014 get close and go graphic.",
    no: "Not quite. Midday portraits suffer, but texture thrives in hard light." },
  { t: "Hold it steady",
    q: "The camera keeps changing exposure between shots and nothing matches. What steadies it?",
    c: ["Manual mode", "Auto ISO", "Scene modes"], a: 0,
    ok: "Correct. Manual locks exposure so every frame matches.",
    no: "Not quite. Auto modes re-meter every shot \u2014 manual holds still." },
  { t: "Hungry autofocus",
    q: "Your camera hunts for focus in low light. What helps most?",
    c: ["Focus on a high-contrast edge", "Keep half-pressing the shutter", "Switch to sports mode"], a: 0,
    ok: "Correct. Autofocus needs contrast \u2014 give it an edge to bite into.",
    no: "Not quite. Low-contrast areas starve the AF system." }
];
